Ugleskopiya/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from Ugleskopiya.settings.base import MEDIA_ROOT, MEDIA_URL
from django.conf.urls.static import static

urlpatterns = [
    path('batya/', admin.site.urls),
    path('', include('apps.app.urls')),
    path('', include('apps.authorization.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

apps/category/models.py
from django.db.models import *
from django.utils.text import slugify
from unidecode import unidecode 

class Category(Model):
    title = CharField('Название категории', max_length=225, unique=True)
    slug = CharField('Slug', max_length=255, blank=True, null=True, unique=True)

    def save(self, *args, **kwargs):
        if not self.slug or self.title != self.slug:
            self.slug = slugify(unidecode(self.title))
            if Category.objects.filter(slug=self.slug).exclude(id=self.id).exists():
                self.slug = f"{self.slug}-{self.id}"
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['-id']

apps/post/models.py
from django.db.models import *
from django.contrib.auth.models import User
from apps.category.models import Category

class Post(Model):
    title = CharField('Заголовок', max_length=225)
    text = TextField('Текст', blank=True, null=True)
    image = ImageField('Фото', upload_to='PostImages', blank=True, null=True)
    category = ManyToManyField(Category, blank=True, null=True, verbose_name='Категория')
    user = ForeignKey(User, on_delete=CASCADE)

    def __str__(self):
        return f'{self.title} {self.user.username}'

    class Meta():
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-id']

apps/user/models.py
from django.db.models import *
from PIL import Image
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

class UserDop(Model):
    user = ForeignKey(User, on_delete=CASCADE)
    image = ImageField('Фото', upload_to='UserImages', default='default/default_coal.png')
    bio = CharField('О себе', max_length=100, default='Сладкий котик ~(=^‥^)/')
    important = BooleanField('Важность чела', default=False)

    def __str__(self):
        return self.bio

    class Meta:
        verbose_name = 'Фото и описание пользователя'
        verbose_name_plural = 'Фото и описании полоьзователей'
        ordering = ['-id']
        
@receiver(post_save, sender=UserDop)
def crop_image(sender, instance, created, **kwargs):
    if instance.image:
        img = Image.open(instance.image.path)
        width, height = img.size
        min_size = min(width, height)
        left = (width - min_size) / 2
        top = (height - min_size) / 2
        right = (width + min_size) / 2
        bottom = (height + min_size) / 2
        img = img.crop((left, top, right, bottom))
        output_size = (200, 200)
        img.thumbnail(output_size)
        img.save(instance.image.path)

@receiver(post_save, sender=User)
def create_userdop(sender, instance, created, **kwargs):
    if created:
        UserDop.objects.create(user=instance)

apps/category/views.py
from django.shortcuts import render

# Create your views here.

apps/post/views.py
from django.shortcuts import render

# Create your views here.

apps/user/views.py
from django.shortcuts import render

# Create your views here.

apps/app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">  
  <title>{% block title %}Ugleskopiya{% endblock %}</title>  
</head>
<body>
  <div class="strip" id="header">
    <a href="{% url 'main' %}">
      <img src="{% static 'images/logo2.png' %}" alt="logo" class="logo"><h1>Ugleskopiya</h1>
    </a>
    <div class="status">
      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Выйти</a>
      {% else %}
        <a href="{% url 'login' %}">Войти</a>
      {% endif %}      
    </div>
    <div class="menu-wrap">
      <input type="checkbox" class="toggler">
      <div class="hamburger">
        <div></div>
      </div>
      <div class="menu">
        <div>
          <div>
            <ul>
              <li><a href="{% url 'main' %}">Главная</a></li>
              <li><a href="{% url 'profil' %}">Ваш профил</a></li>
              <li><a href="{% url 'users' %}">Интересные люди</a></li>
              <li><a href="{% url 'info' %}">О проекте</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% block content %}
  {% endblock %}
</body>
<footer>
  <div class="strip-bottom">
    <p>Вы дошли до конца ленты. Здесь не будут ссылки на наши соцсети, потому что мы позиционируемся как соцсеть (либо мне было лень) ;)</p>
  </div>
</footer>
<div class="oppo"></div>
<script src="{% static 'js/footer.js' %}"></script>
</html>

apps/app/templates/category.html
{% extends 'base.html' %}

{% block title %}{{ category.title }}{% endblock %}

{% block content %}
    <h1 class="category-title">{{ category.title }}</h1>
    {% include 'post.html' %}
{% endblock %}

   

apps/app/templates/conf_page.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/page.css' %}">

<h1>Вы уверены что хотите удалить аккаунт?</h1>
<div>
    <a href="{% url 'delete_user' username=userP.username %}">Да</a>
    <a href="{% url 'main' %}">Нет</a>
</div>

apps/app/templates/edit_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <title>Вход</title>
</head>
<body>
    <div class="wrapper">
        <div class="form-container">
            <div class="form-inner">
                <form action="{% url 'edit_profil' %}" method="post" enctype="multipart/form-data" class="login">
                    {% csrf_token %}
                    <div class="field">
                        {{ form.username }}
                    </div>
                    <div class="field">
                        {{ form.bio }}
                    </div>
                    <div class="field">
                        {{ form.image }}
                    </div>
                    <div class="field btn">
                        <div class="btn-layer"></div>
                        <input type="submit" value="Сохранить" name="edit_profil">
                    </div>
                </form>                               
            </div>
        </div>
    </div>
    <p>Потом доделай страницу, нельзя так оставлять.</p> <style>p {color: rgb(255, 255, 255); text-decoration:underline;}</style>
</body>
</html>

apps/app/templates/info.html
{% extends 'base.html' %}

{% block title %}О нас{% endblock %}

{% block content %}
    <h1 class="trr">Здесь должна была быть очень красивая страница со всеми крутыми фишками дизайна, но мне лень и время поджимает.</h1>
    <style>.trr {margin-top: 100pt;}</style>
{% endblock %}

   

apps/app/templates/logout.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/style.css' %}">  

<div class="logout">
    <h1>
        Ну отлично! Ты вышел из аккаунта! И чего ты этим добился? Зачем тебе это было нужно?
        <a href="{% url 'login' %}">ВЕРНИСЬ!!!!</a> Ну или можешь идти на <a href="{% url 'main' %}">главную страницу.</a> 
    </h1>
    <h2>
        Ты делаешь мне больно :(
    </h2>    
</div>

apps/app/templates/main.html
{% extends 'base.html' %}

{% block title %}Ugleskopiya{% endblock %}

{% block content %}
    {% include 'post.html' %}
{% endblock %}

  

apps/app/templates/post.html
{% for post in posts %}
    <div class="post">
        <a href="{% url 'user' username=post.user.username %}">
            {% if post.user.userdop_set.first.important == False %}<img class="user-ava" src="{{ post.user.userdop_set.first.image.url }}" alt="{{ post.user.username }}">{% endif %}
            {% if post.user.userdop_set.first.important == True %}<img class="superuser-ava" src="{{ post.user.userdop_set.first.image.url }}" alt="{{ post.user.username }}">{% endif %}
            <p>{{ post.user.username }}</p></a>
        {% if post.user == user or user.is_staff %}
            <div class="aaaa">
                <a class="del" href="{% url 'post_delete' pk=post.pk%}">Удалить</a>
                <a href="{% url 'post_edit' pk=post.pk %}">Изменить</a>
            </div>
        {% endif %}
        <div class="postpost">
            <h1>{{ post.title }}</h1>
            {% if post.image %}
                <img src="{{ post.image.url }}" alt="{{ post.title }}">
            {% endif %}
            {% if post.text %}
                <p>{{ post.text }}</p>
            {% endif %}
        </div>
        <div class="category">
            {% if post.category.exists %}
                {% for category in post.category.all %}
                    <a href="{% url 'category' slug=category.slug %}"><p>/{{ category.title }}</p></a>
                {% endfor %}
            {% endif %}
        </div>         
    </div>
{% endfor %}

apps/app/templates/post_edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <title>Изменить пост</title>
</head>
<body>
    <div class="wrapper">
        <div class="form-container">
            <div class="form-inner">
                <form action="{% url 'post_edit' pk=post.pk %}" method="post" enctype="multipart/form-data" class="login">
                    {% csrf_token %}
                    <div class="field">
                        {{ form.title }}
                    </div>
                    <div class="field">
                        {{ form.text }}
                    </div>
                    <div class="field">
                        {{ form.category }}
                    </div>
                    <div class="field">
                        {{ form.image }}
                    </div>
                    <div class="field btn">
                        <div class="btn-layer"></div>
                        <input type="submit" value="Изменить" name="post_edit">
                    </div>
                </form>                               
            </div>
        </div>
    </div>
</body>
</html>

apps/app/templates/profil.html
{% extends 'base.html' %}

{% block title %}Профиль {{ user.username }}{% endblock %}

{% block content %}
    <div class="user-profile">
        {% if user.userdop_set.first.important == False %}
            <div class="user-image">
                <img class="user-ava" src="{{ user.userdop_set.first.image.url }}" alt="{{ user.username }}">
            </div>
        {% endif %}
        {% if user.userdop_set.first.important == True %}
            <div class="superuser-image">
                <img class="superuser-ava" src="{{ user.userdop_set.first.image.url }}" alt="{{ user.username }}">
            </div>
        {% endif %}
        <div class="user-info">
            <h1>{{ user.username }}</h1>
            <h3>{{ user.userdop_set.first.bio }}</h3>
            <h6>с нами с {{ user.date_joined }}</h6>
        </div>
        <a class="linka" href="edit_profil">Изменить данные</a>
        <a class="linka" href="{% url 'conf_page' username=user.username %}">Удалить аккаунт</a>
    </div>

    {% include 'post.html' %}

    <div class="post-form">
        <form action="{% url 'profil' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Запостить" name="post">
        </form>
    </div>

{% endblock %}

   

apps/app/templates/user.html
{% extends 'base.html' %}

{% block title %}{{ userP.username }}{% endblock %}

{% block content %}

    <div class="user-profile">
        {% if userP.userdop_set.first.important == False %}
            <div class="user-image">
                <img class="user-ava" src="{{ userP.userdop_set.first.image.url }}" alt="{{ userP.username }}">
            </div>
        {% endif %}
        {% if userP.userdop_set.first.important == True %}
            <div class="superuser-image">
                <img class="superuser-ava" src="{{ userP.userdop_set.first.image.url }}" alt="{{ userP.username }}">
            </div>
        {% endif %}
        <div class="user-info">
            <h1>{{ userP.username }}</h1>
            <h3>{{ userP.userdop_set.first.bio }}</h3>
            <h6>с нами с {{ userP.date_joined }}</h6>
        </div>
        {% if user == userP or user.is_staff %}
            <a class="linka" href="{% url 'conf_page' username=userP.username %}">Удалить аккаунт</a>
        {% endif %}
    </div>

    {% include 'post.html' %}

{% endblock %}

  

apps/app/templates/users.html
{% extends 'base.html' %}

{% block title %}Интересные люди{% endblock %}

{% block content %}
    <h1 class="users-title">Наши котики</h1>
    {% for user in users %}
        <a class="aa" href="{% url 'user' username=user.username %}">
            <div class="userobj">
                    {% if user.userdop_set.first.important == False %}<img class="user-ava" src="{{ user.userdop_set.first.image.url }}" alt="{{ user.username }}">{% endif %}
                    {% if user.userdop_set.first.important == True %}<img class="superuser-ava" src="{{ user.userdop_set.first.image.url }}" alt="{{ user.username }}">{% endif %}
            <div class="userobj2">
                <h1>{{ user.username }}</h1>
                <p>{{ user.userdop_set.first.bio }}</p>
            </div>
            </div>
        </a>
    {% endfor %}
{% endblock %}

 